# Generated by Django 3.2 on 2023-01-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da foto')),
                ('place', models.CharField(max_length=100, verbose_name='Local da foto')),
                ('date', models.DateField(verbose_name='Data da foto')),
                ('photographer', models.DateField(max_length=100, verbose_name='Local da foto')),
                ('camera_flash', models.BooleanField(verbose_name='Flash da Câmera')),
            ],
        ),
    ]
