# Generated by Django 3.2 on 2023-01-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photographer',
            field=models.CharField(max_length=100, verbose_name='Nome do fotógrafo'),
        ),
    ]
